name: ABX Peristence Workflow


on:
  push:
  pull_request:

permissions:
  packages: write   # Allows write access to GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: abx
          MYSQL_USER: abx
          MYSQL_PASSWORD: admin
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Graalvm
        uses: graalvm/setup-graalvm@v1.2.6
        with:
          java-version:  '21.0.5'

      - name: Settings
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: '[
            {"id": "github-ABXUSArch","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}},
            {"id": "github-ABXPersistence","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}}
          ]'

            # Step 3: Compile and deploy ABX Persistence
      - name: Compile and deploy ABX Persistence
        run: |
          mvn deploy
